### ISSUE TITLE
Consider adding methods under field of contract object

### ISSUE THREAD

**Issue by austinabell** [near/near-abi-client-js#9]
Currently the API attaches functions for each function in the ABI based on name, but this can cause issues if the function name overlaps with one of the functions we currently do or will support in the future.

Might be the safest to just have a `methods` field on the contract. Worth getting input from someone with more JS exp than me.

Benefits:
- Improves typing for the `AnyContract` object. Currently there are no types available since the wildcard on the fields of the contract overwrites the TS types
- Avoids overlap and potentially buggy behaviour

Cons:
- Can't call the method on the contract object directly (slightly less ergonomic):
```ts
contract.add([1, 2], [3, 4], 5);

// Would be
contract.methods.add([1, 2], [3, 4], 5);
```

**Comment by miraclx** [comment]
I agree with this. As a case study, we can look at the two most popular web3 client libraries in JS;

`web3js` takes the `contract.methods.add` approach, returning an object with `send` (view) and `call` (change) methods. https://web3js.readthedocs.io/en/v1.8.0/web3-eth-contract.html#id28

> ```js
> let sum = await contract.methods.add([1, 2], [3, 4], 5).call();
> ```

Whereas `ethersjs` takes the `contract.add` approach, making a view / change call depending on the method definition in the ABI. https://docs.ethers.io/v5/api/contract/example/#erc20-meta-methods

> ```js
> let sum = await contract.add([1, 2], [3, 4], 5);
> ```

As for how they avoid collisions, since Solidity allows function overloading, both of these libraries also provide the raw function signatures.

`web3js`

> ```js
> let sum = await contract.methods.add([1, 2], [3, 4], 5).call()
> let sum = await contract.methods['add(uint256[], uint256[], uint256)']([1, 2], [3, 4], 5).call()
> let sum = await contract.methods['0x58cf5f10']([1, 2], [3, 4], 5).call()
> ```

And finally, since `ethersjs` injects the methods directly into the `Contract` object, it simply doesn't add methods that already exist in the `Contract` object or have overrides in the ABI.

> ```js
> let sum = await contract.add([1, 2], [3, 4], 5)
> let sum = await contract['add(uint256[], uint256[], uint256)']([1, 2], [3, 4], 5)
> let sum = await contract['0x58cf5f10']([1, 2], [3, 4], 5)
> ```

Personally, I think the `contract.methods._.{view,call}` flow is preferable. Especially since our case is even less generic.
